controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check

index:
    path: /{wildcard}
    controller: App\Controller\AppController::index
    requirements:
        wildcard: .*